#!/usr/bin/env python3
"""
build_feeds.py — fetch consulting/business RSS feeds and write feeds.json.

Runs in GitHub Actions (full internet) where browser CORS does not apply, so it
can pull McKinsey/BCG/etc. directly. Feeds that fail or have no public RSS are
skipped gracefully — the playbook falls back to a direct link for those sources.

Local use:  pip install feedparser && python scripts/build_feeds.py
"""
import json, datetime, sys
import feedparser

ITEMS_PER_SOURCE = 6

# key, display name, candidate feed URL(s) tried in order. Link-only sources
# (no reliable public RSS) are intentionally omitted here; the playbook links them.
SOURCES = [
    ("mckinsey", "McKinsey Insights", [
        "https://www.mckinsey.com/insights/rss",
        "http://www.mckinsey.com/insights/rss.aspx",
    ]),
    ("bcg", "BCG Publications", [
        "https://www.bcg.com/publications/rss",
    ]),
    ("hbr", "Harvard Business Review", [
        "https://feeds.hbr.org/harvardbusiness",
    ]),
    ("hbr_pod", "HBR Podcasts (IdeaCast)", [
        "https://feeds.hbr.org/harvardbusiness/ideacast",
    ]),
    ("sloan", "MIT Sloan Management Review", [
        "https://sloanreview.mit.edu/feed/",
    ]),
    ("wharton", "Knowledge at Wharton", [
        "https://knowledge.wharton.upenn.edu/feed/",
    ]),
    ("deloitte", "Deloitte Insights", [
        "https://www2.deloitte.com/us/en/insights/rss-feeds.rss",
        "https://www2.deloitte.com/insights/us/en/rss.xml",
    ]),
]

def parse_date(entry):
    for attr in ("published_parsed", "updated_parsed"):
        t = entry.get(attr)
        if t:
            try:
                return datetime.datetime(*t[:6]).isoformat()
            except Exception:
                pass
    return None

def fetch(urls):
    for url in urls:
        try:
            d = feedparser.parse(url)
            if d.entries:
                items = []
                for e in d.entries[:ITEMS_PER_SOURCE]:
                    title = (e.get("title") or "").strip()
                    link = (e.get("link") or "").strip()
                    if title and link:
                        items.append({"title": title, "link": link, "date": parse_date(e)})
                if items:
                    return items, url
        except Exception as ex:
            print(f"  ! {url}: {ex}", file=sys.stderr)
    return [], None

def main():
    out_sources = []
    for key, name, urls in SOURCES:
        items, used = fetch(urls)
        status = f"{len(items)} items via {used}" if items else "no feed — link-only fallback"
        print(f"{name}: {status}")
        out_sources.append({"key": key, "name": name, "items": items})
    payload = {
        "updated": datetime.datetime.utcnow().isoformat() + "Z",
        "note": "Auto-generated by build_feeds.py via GitHub Actions.",
        "sources": out_sources,
    }
    with open("feeds.json", "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
    total = sum(len(s["items"]) for s in out_sources)
    print(f"\nWrote feeds.json with {total} total items across {len(out_sources)} sources.")

if __name__ == "__main__":
    main()
